#!/bin/sh

ls Allan-Bold.png
ls Allerta-Medium.png
ls AnonymousPro-Regular.png
ls Arimo-Regular-Latin.png
ls Arvo-Regular.png
ls Bentham-Regular.png
ls Buda-Light.png
ls Cabin-Bold.png
ls Calligraffiti.png
ls Cantarell-Regular.png
ls Cardo99s.png
ls CherryCreamSoda.png
ls Chewy.png
ls Coda-Heavy.png
ls ComingSoon.png
ls Copse-Regular.png
ls Corben-Bold.png
ls Cousine-Regular-Latin.png
ls CoveredByYourGrace.png
ls CraftyGirls.png
ls CrimsonText-Roman.png
ls Crushed.png
ls Cuprum.png
ls DroidSans.png
ls FontdinerSwanky.png
ls Geo-Regular.png
ls GFSDidot-Regular.png
ls GFSNeohellenic.png
ls Gruppo-Light.png
ls Hanuman.png
ls HomemadeApple.png
ls IMFeENrm28P.png
ls Inconsolata.png
ls IrishGrowler.png
ls JosefinSans-Regular.png
ls JosefinSlab-Regular.png
ls JustAnotherHand.png
ls JustMeAgainDownHere.png
ls YanoneKaffeesatz-Regular.png
ls Kenia-Regular.png
ls Kranky.png
ls Kristi.png
ls Lato-Regular.png
ls Lekton-Regular.png
ls Lobster.png
ls LuckiestGuy.png
ls Merriweather.png
ls Molengo-Regular.png
ls MountainsofChristmas.png
ls Neucha.png
ls Neuton.png
ls nobile.png
ls Orbitron-Regular.png
ls PermanentMarker.png
ls Philosopher.png
ls PT_Sans-Regular.png
ls Puritan-Regular.png
ls Raleway-Thin.png
ls ReenieBeanie.png
ls RockSalt.png
ls Schoolbell.png
ls Slackey.png
ls Sniglet-Regular.png
ls Sunshiney.png
ls Syncopate.png
ls Tangerine_Regular.png
ls Tinos-Regular-Latin.png
ls Ubuntu-Regular.png
ls UnifrakturCook-Bold.png
ls UnifrakturMaguntia-Book.png
ls Unkempt.png
ls Vibur-Regular.png
ls Vollkorn-Regular.png
ls WalterTurncoat.png


