#!/bin/sh

ls Allan-Bold.ttf
ls Allerta-Medium.ttf
ls AnonymousPro-Regular.ttf
ls Arimo-Regular-Latin.ttf
ls Arvo-Regular.ttf
ls Bentham-Regular.ttf
ls Buda-Light.ttf
ls Cabin-Bold.ttf
ls Calligraffiti.ttf
ls Cantarell-Regular.ttf
ls Cardo99s.ttf
ls CherryCreamSoda.ttf
ls Chewy.ttf
ls Coda-Heavy.ttf
ls ComingSoon.ttf
ls Copse-Regular.ttf
ls Corben-Bold.ttf
ls Cousine-Regular-Latin.ttf
ls CoveredByYourGrace.ttf
ls CraftyGirls.ttf
ls CrimsonText-Roman.ttf
ls Crushed.ttf
ls Cuprum.ttf
ls DroidSans.ttf
ls FontdinerSwanky.ttf
ls Geo-Regular.ttf
ls GFSDidot-Regular.ttf
ls GFSNeohellenic.ttf
ls Gruppo-Light.ttf
ls Hanuman.ttf
ls HomemadeApple.ttf
ls IMFeENrm28P.ttf
ls Inconsolata.ttf
ls IrishGrowler.ttf
ls JosefinSans-Regular.ttf
ls JosefinSlab-Regular.ttf
ls JustAnotherHand.ttf
ls JustMeAgainDownHere.ttf
ls YanoneKaffeesatz-Regular.ttf
ls Kenia-Regular.ttf
ls Kranky.ttf
ls Kristi.ttf
ls Lato-Regular.ttf
ls Lekton-Regular.ttf
ls Lobster.ttf
ls LuckiestGuy.ttf
ls Merriweather.ttf
ls Molengo-Regular.ttf
ls MountainsofChristmas.ttf
ls Neucha.ttf
ls Neuton.ttf
ls nobile.ttf
ls Orbitron-Regular.ttf
ls PermanentMarker.ttf
ls Philosopher.ttf
ls PT_Sans-Regular.ttf
ls Puritan-Regular.ttf
ls Raleway-Thin.ttf
ls ReenieBeanie.ttf
ls RockSalt.ttf
ls Schoolbell.ttf
ls Slackey.ttf
ls Sniglet-Regular.ttf
ls Sunshiney.ttf
ls Syncopate.ttf
ls Tangerine_Regular.ttf
ls Tinos-Regular-Latin.ttf
ls Ubuntu-Regular.ttf
ls UnifrakturCook-Bold.ttf
ls UnifrakturMaguntia-Book.ttf
ls Unkempt.ttf
ls Vibur-Regular.ttf
ls Vollkorn-Regular.ttf
ls WalterTurncoat.ttf



