#!/bin/sh

ls GFSDidot-Regular.ttf
ls Allan.ttf
ls Allerta-Medium.ttf
ls AnonymousPro.ttf
ls Arimo.ttf
ls Arvo.ttf
ls Bentham-Regular.ttf
ls Buda.ttf
ls Cabin-Bold.ttf
ls Calligraffitti.ttf
ls Cantarell-Regular.ttf
ls Cardo.ttf
ls CherryCreamSoda.ttf
ls Chewy.ttf
ls Coda-Heavy.ttf
ls ComingSoon.ttf
ls Copse.ttf
ls Corben.ttf
ls Cousine.ttf
ls CoveredByYourGrace.ttf
ls CraftyGirls.ttf
ls CrimsonText-Roman.ttf
ls Crushed-Regular.ttf
ls Cuprum.ttf
ls DroidSans.ttf
ls FontdinerSwanky.ttf
ls Geo-Regular.ttf
ls GFSDidot-Regular.ttf
ls GFSNeohellenic-Regular.ttf
ls Gruppo.ttf
ls hanuman.ttf
ls HomemadeApple.ttf
ls IM_FELL_English_Roman.ttf
ls Inconsolata.ttf
ls IrishGrowler.ttf
ls JosefinSans.ttf
ls JosefinSlab.ttf
ls JustAnotherHand-Regular.ttf
ls JustMeAgainDownHere.ttf
ls YanoneKaffeesatz-Regular.ttf
ls Kenia-Regular.ttf
ls Kranky.ttf
ls Kristi.ttf
ls Lato.ttf
ls Lekton-Regular.ttf
ls Lobster.ttf
ls LuckiestGuy-Regular.ttf
ls Merriweather.ttf
ls Molengo.ttf
ls MountainsofChristmas-Regular.ttf
ls Neucha.ttf
ls Neuton.ttf
ls Nobile.ttf
ls Orbitron-Regular.ttf
ls PermanentMarker.ttf
ls Philosopher.ttf
ls PTSans-Regular.ttf
ls Puritan-Regular.ttf
ls Raleway-Thin.ttf
ls ReenieBeanie.ttf
ls RockSalt.ttf
ls Schoolbell.ttf
ls Slackey.ttf
ls Sniglet.ttf
ls Sunshiney.ttf
ls Syncopate-Regular.ttf
ls Tangerine.ttf
ls Tinos.ttf
ls Ubuntu-Regular.ttf
ls UnifrakturCook.ttf
ls UnifrakturMaguntia.ttf
ls Unkempt.ttf
ls Vibur-Regular.ttf
ls Vollkorn-Regular.ttf
ls WalterTurncoat.ttf

